export const EVENT_TYPES = [
  { id: 'sale', label: 'Vendí algo', icon: '💰', color: 'green' },
  { id: 'purchase', label: 'Compré algo', icon: '🛒', color: 'orange' },
  { id: 'expense', label: 'Pagué algo', icon: '📤', color: 'red' },
  { id: 'ar_payment', label: 'Me pagaron', icon: '📥', color: 'blue' },
  { id: 'obligation_received', label: 'Me prestaron', icon: '🤝', color: 'purple' },
  { id: 'obligation_payment', label: 'Pagué deuda', icon: '🏦', color: 'purple' },
  { id: 'transfer', label: 'Transferí', icon: '🔄', color: 'gray' },
  { id: 'capital_contribution', label: 'Aporte capital', icon: '📈', color: 'green' },
  { id: 'adjustment', label: 'Ajuste', icon: '📊', color: 'gray' },
] as const

export const PAYMENT_TYPES = [
  { id: 'cash', label: 'Efectivo', icon: '💵' },
  { id: 'nequi', label: 'Nequi', icon: '📱' },
  { id: 'daviplata', label: 'Daviplata', icon: '📱' },
  { id: 'tc', label: 'Tarjeta crédito', icon: '💳' },
  { id: 'td', label: 'Tarjeta débito', icon: '💳' },
  { id: 'transfer', label: 'Transferencia', icon: '🏦' },
  { id: 'credit', label: 'Crédito', icon: '📝' },
  { id: 'partial', label: 'Parcial', icon: '🔀' },
] as const

export const OBLIGATION_TYPES = [
  { id: 'rent', label: 'Arriendo', category: 'Gastos Fijos', icon: '🏠', color: 'blue' },
  { id: 'payroll', label: 'Nómina', category: 'Gastos Fijos', icon: '👥', color: 'blue' },
  { id: 'electricity', label: 'Electricidad', category: 'Gastos Fijos', icon: '⚡', color: 'warning' },
  { id: 'water', label: 'Agua', category: 'Gastos Fijos', icon: '💧', color: 'info' },
  { id: 'gas', label: 'Gas', category: 'Gastos Fijos', icon: '🔥', color: 'warning' },
  { id: 'internet', label: 'Internet', category: 'Gastos Fijos', icon: '🌐', color: 'info' },
  { id: 'telephone', label: 'Teléfono', category: 'Gastos Fijos', icon: '📞', color: 'info' },
  { id: 'security', label: 'Seguridad', category: 'Gastos Fijos', icon: '🛡️', color: 'muted' },
  { id: 'cleaning', label: 'Aseo', category: 'Gastos Fijos', icon: '🧹', color: 'muted' },
  { id: 'accounting', label: 'Contabilidad', category: 'Gastos Fijos', icon: '📊', color: 'blue' },
  { id: 'insurance', label: 'Seguros', category: 'Gastos Fijos', icon: '🛡️', color: 'success' },
  { id: 'vehicle_expenses', label: 'Gastos vehículos', category: 'Gastos Fijos', icon: '🚗', color: 'warning' },
  { id: 'equipment_leasing', label: 'Arriendo equipos', category: 'Gastos Fijos', icon: '⚙️', color: 'muted' },
  { id: 'bank_loan', label: 'Préstamo bancario', category: 'Obligaciones Financieras', icon: '🏦', color: 'blue' },
  { id: 'partner_loan', label: 'Préstamo de socio', category: 'Obligaciones Financieras', icon: '🤝', color: 'purple' },
  { id: 'supplier_credit', label: 'Crédito proveedor', category: 'Obligaciones Financieras', icon: '📦', color: 'warning' },
  { id: 'credit_card', label: 'Tarjeta de crédito', category: 'Obligaciones Financieras', icon: '💳', color: 'danger' },
  { id: 'vehicle_financing', label: 'Financiamiento vehículo', category: 'Obligaciones Financieras', icon: '🚗', color: 'blue' },
  { id: 'leasing', label: 'Leasing', category: 'Obligaciones Financieras', icon: '📋', color: 'muted' },
  { id: 'vat', label: 'IVA', category: 'Obligaciones Tributarias', icon: '📄', color: 'danger' },
  { id: 'income_tax', label: 'Renta', category: 'Obligaciones Tributarias', icon: '💰', color: 'danger' },
  { id: 'municipal_taxes', label: 'Impuestos municipales', category: 'Obligaciones Tributarias', icon: '🏙️', color: 'warning' },
  { id: 'payroll_taxes', label: 'Parafiscales', category: 'Obligaciones Tributarias', icon: '👥', color: 'warning' },
  { id: 'social_security', label: 'Seguridad social', category: 'Obligaciones Tributarias', icon: '🏥', color: 'success' },
  { id: 'google_workspace', label: 'Google Workspace', category: 'Servicios Digitales', icon: '📧', color: 'info' },
  { id: 'microsoft365', label: 'Microsoft 365', category: 'Servicios Digitales', icon: '💻', color: 'info' },
  { id: 'adobe', label: 'Adobe', category: 'Servicios Digitales', icon: '🎨', color: 'danger' },
  { id: 'canva', label: 'Canva', category: 'Servicios Digitales', icon: '🖼️', color: 'info' },
  { id: 'chatgpt', label: 'ChatGPT', category: 'Servicios Digitales', icon: '🤖', color: 'success' },
  { id: 'hosting', label: 'Hosting', category: 'Servicios Digitales', icon: '🌍', color: 'blue' },
  { id: 'domains', label: 'Dominios', category: 'Servicios Digitales', icon: '🔗', color: 'blue' },
  { id: 'cloud', label: 'Servicios cloud', category: 'Servicios Digitales', icon: '☁️', color: 'info' },
  { id: 'maintenance', label: 'Contratos mantenimiento', category: 'Otros', icon: '🔧', color: 'warning' },
  { id: 'software_licenses', label: 'Licencias software', category: 'Otros', icon: '📦', color: 'purple' },
  { id: 'recurring_services', label: 'Servicios recurrentes', category: 'Otros', icon: '🔄', color: 'muted' },
  { id: 'other', label: 'Otro', category: 'Otros', icon: '📋', color: 'muted' },
] as const

export const OBLIGATION_CATEGORIES = [
  'Gastos Fijos',
  'Obligaciones Financieras',
  'Obligaciones Tributarias',
  'Servicios Digitales',
  'Otros',
] as const

export const OBLIGATION_FREQUENCIES = [
  { id: 'once', label: 'Único pago' },
  { id: 'weekly', label: 'Semanal' },
  { id: 'biweekly', label: 'Quincenal' },
  { id: 'monthly', label: 'Mensual' },
  { id: 'quarterly', label: 'Trimestral' },
  { id: 'semiannual', label: 'Semestral' },
  { id: 'annual', label: 'Anual' },
] as const

export const OBLIGATION_PRIORITIES = [
  { id: 'low', label: 'Baja', color: 'muted' },
  { id: 'normal', label: 'Normal', color: 'info' },
  { id: 'high', label: 'Alta', color: 'warning' },
  { id: 'critical', label: 'Crítica', color: 'danger' },
] as const

export const SIDEBAR_ITEMS = [
  { label: 'Dashboard', href: '/dashboard', icon: 'LayoutDashboard' },
  { label: 'Caja', href: '/cash', icon: 'Wallet' },
  { label: 'Bancos', href: '/banks', icon: 'Building2' },
  { label: 'Tesorería', href: '/treasury', icon: 'TrendingUp' },
  { section: 'Operaciones' },
  { label: 'Ventas', href: '/sales', icon: 'ShoppingBag' },
  { label: 'Gastos', href: '/expenses', icon: 'Receipt' },
  { label: 'Compras', href: '/purchases', icon: 'Package' },
  { label: 'Proveedores', href: '/suppliers', icon: 'Users' },
  { section: 'Obligaciones' },
  { label: 'CxC', href: '/receivables', icon: 'ArrowDownLeft' },
  { label: 'CxP', href: '/payables', icon: 'ArrowUpRight' },
  { label: 'Obligaciones', href: '/obligations', icon: 'Scale' },
  { section: 'Patrimonio' },
  { label: 'Activos', href: '/assets', icon: 'Box' },
  { label: 'Documentos', href: '/documents', icon: 'FileText' },
  { section: 'Sistema' },
  { label: 'Auditoría', href: '/audit', icon: 'ShieldCheck' },
  { label: 'Reportes', href: '/reports', icon: 'BarChart3' },
  { label: 'Configuración', href: '/settings', icon: 'Settings' },
]
