[build]
  command = "npx prisma generate && npx next build"

[build.environment]
  NODE_VERSION = "22"
  NEXT_EXPERIMENTAL_COMPILE_CACHE = "1"
  TZ = "America/Bogota"

[[plugins]]
  package = "@netlify/plugin-nextjs"


